// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBm8IFKyxqhp2WR00cHTqlFYxfwokvJVs',
    appId: '1:547624212456:web:77ba247541bebf346af65d',
    messagingSenderId: '547624212456',
    projectId: 'wireless-demo',
    authDomain: 'wireless-demo.firebaseapp.com',
    storageBucket: 'wireless-demo.appspot.com',
    measurementId: 'G-V6RV8D94QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbwOCC5Kkp8V__9Eb7O_gqhVx9kc_xwB4',
    appId: '1:547624212456:android:503bddf46099693e6af65d',
    messagingSenderId: '547624212456',
    projectId: 'wireless-demo',
    storageBucket: 'wireless-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKu9Pyse4xRLaLZ81YOaOu0R-aKppM8YY',
    appId: '1:547624212456:ios:8afdc9164ff5dbe96af65d',
    messagingSenderId: '547624212456',
    projectId: 'wireless-demo',
    storageBucket: 'wireless-demo.appspot.com',
    iosBundleId: 'com.example.rorich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKu9Pyse4xRLaLZ81YOaOu0R-aKppM8YY',
    appId: '1:547624212456:ios:b55bbb5331abdbd06af65d',
    messagingSenderId: '547624212456',
    projectId: 'wireless-demo',
    storageBucket: 'wireless-demo.appspot.com',
    iosBundleId: 'com.example.rorich.RunnerTests',
  );
}
